#!/usr/bin/env bash
#uses while if elif and else to display best school everytime except the 4th and 8th time where it displays bad luck and good luck respectivly.
i=1
while ((i<=10)) ; do
	if [ $i = 8 ]; then
		echo "good luck"
	elif [ $i = 4 ]; then
		echo "bad luck"
	else
		echo "Best School"
	fi
	((i++))
done
