#!/usr/bin/env bash
#uses while and case to display numbers from 1-20 and show bad luck supersitious numbers from their respective countries.
i=1
while ((i<=20)); do
case $i in
	4)
	   echo "$i"		
	   echo "bad luck from China"
	;;

	9)
	   echo "$i"	
	   echo "bad luck from Japan"
	;;

	17)
	   echo "$i"	
	   echo "bad luck from Italy"
	;;

	*)
	  echo "$i"
	;;
esac
	((i++))
done
